"""added the creator of a fridge

Revision ID: 0149a2e7e07a
Revises: 2cc284c4271e
Create Date: 2020-03-24 10:50:41.830069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0149a2e7e07a'
down_revision = '2cc284c4271e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridge', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fridge', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fridge', type_='foreignkey')
    op.drop_column('fridge', 'creator_id')
    # ### end Alembic commands ###
