"""rem col

Revision ID: 07f5eea56312
Revises: d70794ca2869
Create Date: 2020-03-31 17:50:28.840709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.models import Product, Item

# revision identifiers, used by Alembic.
revision = '07f5eea56312'
down_revision = 'd70794ca2869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'natrium')
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for p in session.query(Item):
        p.initQty = 1
    session.commit()


    for p in session.query(Product):
        barcode = p.barcode
        if(int(barcode[0:2]) == 21 or int(barcode[0:2]) == 5):
            p.barcode = barcode[2:7]

    session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('natrium', sa.REAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
