"""added uuid to products

Revision ID: 0efb01b11849
Revises: 866a84fc0e68
Create Date: 2020-03-13 20:49:46.970607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0efb01b11849'
down_revision = '866a84fc0e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'uuid')
    # ### end Alembic commands ###
