"""change suger to sugar

Revision ID: 450c23646868
Revises: 8adf80afd550
Create Date: 2020-02-19 00:38:04.878209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450c23646868'
down_revision = '8adf80afd550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('carbs_sugar', sa.Float(precision=2), nullable=True))
    op.drop_column('product', 'carbs_suger')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('carbs_suger', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('product', 'carbs_sugar')
    # ### end Alembic commands ###
