"""2 nullable category_id on product to false

Revision ID: 5ea9755ea455
Revises: 17b695de659f
Create Date: 2020-03-31 11:34:43.231308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from app.models import Product

# revision identifiers, used by Alembic.
revision = '5ea9755ea455'
down_revision = '17b695de659f'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for p in session.query(Product).filter_by(category_id=None):
        p.category_id = 9

    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
