"""added item

Revision ID: 698a3660ca7c
Revises: f695a4a3e158
Create Date: 2020-03-14 00:47:35.986357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '698a3660ca7c'
down_revision = 'f695a4a3e158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('fridge_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridge.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
