"""add field initQty to items table

Revision ID: 6ad92d97710a
Revises: 9eb990c58ccd
Create Date: 2020-03-31 14:46:32.545676

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import orm
from app.models import Product, Item

# revision identifiers, used by Alembic.
revision = '6ad92d97710a'
down_revision = '9eb990c58ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('initQty', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    for p in session.query(Item):
        p.initQty = 1

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'initQty')
    # ### end Alembic commands ###
