"""added nutrient facts

Revision ID: 70418c9d5ffc
Revises: a058cde1ccb5
Create Date: 2020-02-04 14:50:19.647790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70418c9d5ffc'
down_revision = 'a058cde1ccb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('carbs', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('carbs_suger', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('energy_kcal', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('fat', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('fat_saturated', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('fiber', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('natrium', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('nutrientbase', sa.Enum('hundred_gramm', 'hundred_milliliter', name='nutrientbase'), nullable=True))
    op.add_column('product', sa.Column('protein', sa.Float(precision=2), nullable=True))
    op.add_column('product', sa.Column('salt', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'salt')
    op.drop_column('product', 'protein')
    op.drop_column('product', 'nutrientbase')
    op.drop_column('product', 'natrium')
    op.drop_column('product', 'fiber')
    op.drop_column('product', 'fat_saturated')
    op.drop_column('product', 'fat')
    op.drop_column('product', 'energy_kcal')
    op.drop_column('product', 'carbs_suger')
    op.drop_column('product', 'carbs')
    # ### end Alembic commands ###
