"""init

Revision ID: 8adf80afd550
Revises: 
Create Date: 2020-02-19 00:09:32.832193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adf80afd550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('displayname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('qty_type', sa.Enum('gramm', 'milliliter', 'pieces', name='quantitytype'), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('nutrientbase', sa.Enum('hundred_gramm', 'hundred_milliliter', name='nutrientbase'), nullable=True),
    sa.Column('energy_kcal', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Float(precision=2), nullable=True),
    sa.Column('fat_saturated', sa.Float(precision=2), nullable=True),
    sa.Column('salt', sa.Float(precision=2), nullable=True),
    sa.Column('protein', sa.Float(precision=2), nullable=True),
    sa.Column('carbs', sa.Float(precision=2), nullable=True),
    sa.Column('carbs_suger', sa.Float(precision=2), nullable=True),
    sa.Column('fiber', sa.Float(precision=2), nullable=True),
    sa.Column('natrium', sa.Float(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
