"""remove null value

Revision ID: 9eb990c58ccd
Revises: 5ea9755ea455
Create Date: 2020-03-31 12:25:29.560408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb990c58ccd'
down_revision = '5ea9755ea455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
