"""add isadmin flag to user

Revision ID: c57761cd6fae
Revises: 450c23646868
Create Date: 2020-02-19 21:04:03.997303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57761cd6fae'
down_revision = '450c23646868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_product')
    op.add_column('user', sa.Column('isadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isadmin')
    op.create_table('_product',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=31), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=30), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('qty_type', sa.VARCHAR(length=10), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('qty', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.VARCHAR(length=5), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('carbs_suger', sa.VARCHAR(length=5), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('energy_kcal', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('fat', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('fat_saturated', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('fiber', sa.VARCHAR(length=3), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('natrium', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('nutrientbase', sa.VARCHAR(length=13), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('protein', sa.VARCHAR(length=4), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('salt', sa.VARCHAR(length=5), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
