"""add col

Revision ID: d70794ca2869
Revises: 6ad92d97710a
Create Date: 2020-03-31 17:50:02.222406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70794ca2869'
down_revision = '6ad92d97710a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('natrium', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'natrium')
    # ### end Alembic commands ###
