"""empty message

Revision ID: d87b854f1d1c
Revises: 45fb547f03cd
Create Date: 2020-02-18 13:49:01.782338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87b854f1d1c'
down_revision = '45fb547f03cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DATETIME(), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=1)
    # ### end Alembic commands ###
